### ISSUE TITLE
Gem recently broke for retrieving Models based on Make, suspect API

### ISSUE THREAD

**Issue by frankpinto** [Sovietaced/edmunds#11]
Just tested:

`Edmunds::Vehicle::Specification::Model::Models.find('Toyota')`

and its now returning 502 Bad Gateway. We use this gem in our main user facing site at lendbuzz.com, I'm pretty positive it broke in the past few days. We were getting some emails from Edmunds about API changes - that might be the issue.

I'm going to investigate further and see if I can put together a pull request but if you know how to fix it fast @Sovietaced, I'd appreciate it.

**Comment by frankpinto** [comment]
Turns out its an issue with the actual endpoint, already emailed Edmunds about it, closing this issue.

**Comment by Sovietaced** [comment]
Thanks for looking into it.
