### ISSUE TITLE
Developer Inactive Error

### ISSUE THREAD

**Issue by carltonsmith** [Sovietaced/edmunds#9]
I'm having an error using this in Rails. When I use it locally it works as expected, but when I've rolled it to the production environment I am getting a "Developer Inactive" error back. It seems to be set up correctly on the server, as it works when I call it from the rails console (using the same code that is erroring on the site). Not sure how I can possibly debug this as it seems to be a problem in the gem.

**Comment by Sovietaced** [comment]
@carltonsmith I just pushed out 0.0.8 
Can you give this another shot?

**Comment by Sovietaced** [comment]
@carltonsmith After doing some short research this looks like the error message that is returned along with a 403 error. This would mean that the auth configuration in your production environment settings are wrong. Did you ever get this worked out?

**Comment by carltonsmith** [comment]
Yes, it was an auth configuration issue. It’s all set now.

**Comment by Sovietaced** [comment]
@carltonsmith Cool. Closing this then.
